name: Build and deploy ASP.Net Core app to Azure Web App - nency-dotnet-core-application

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.x'           # set this to the dot net version to use
  ROOT_PATH: './calculator'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '8.x'
          include-prerelease: true

    - name: Restore
      run: dotnet restore
        
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ${{env.ROOT_PATH}}
    
    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      working-directory: ${{env.ROOT_PATH}}

    - name: Zip myapp folder
      run: zip -r ${{env.DOTNET_ROOT}}/myapp.zip ${{env.DOTNET_ROOT}}/myapp
      working-directory: ${{env.ROOT_PATH}}

    - name: Compress artifact
      run: gzip -c ${{env.DOTNET_ROOT}}/myapp.zip > ${{env.DOTNET_ROOT}}/myapp.gz
      working-directory: ${{env.DOTNET_ROOT}}
    
    - name: Upload compressed artifact
      uses: actions/upload-artifact@v3
      with:
          name: .net-app-gz
          path: ${{env.DOTNET_ROOT}}/myapp.gz
          retention-days: 1
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:        
      - name: Download compressed artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app-gz

      - name: Uncompress artifact
        run: gzip -d ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp.gz
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
      - name: Check if myapp.zip exists
        run: ls -l myapp.zip

      - name: Unzip artifact
        run: unzip myapp.zip -d myapp_unzipped
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
      - name: Upload uncompressed artifact for deployment
        uses: actions/upload-artifact@v3
        with:
            name: .net-app-unzipped
            path: myapp_unzipped
            retention-days: 1

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nency-dotnet-core-application'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7DA76E03FA3D4A729711506FA98F7219 }}
          package: myapp_unzipped
