name: Build and deploy ASP.Net Core app to Azure Web App - nency-dotnet-core-application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Verify myapp directory contents
        run: |
          ls -la ${{env.DOTNET_ROOT}}/myapp
        shell: bash

      - name: Compress artifact
        run: zip -r ${{env.DOTNET_ROOT}}/myapp.zip ${{env.DOTNET_ROOT}}/myapp
        shell: bash

      - name: Verify compression result
        run: |
          ls -la ${{env.DOTNET_ROOT}}/myapp.zip
        shell: bash

      - name: Upload compressed artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: ${{env.DOTNET_ROOT}}/myapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: myapp
  
      - name: List contents of downloaded artifact
        run: |
          ${{ env.DOTNET_ROOT }} ls -la 
          pwd
        shell: bash
  
      - name: Unzip artifact
        run: unzip "${{ github.workspace }}/myapp.zip" -d "${{ github.workspace }}/myapp"
        shell: bash
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nency-dotnet-core-application'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7DA76E03FA3D4A729711506FA98F7219 }}
          package: ${{ github.workspace }}/myapp
