# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy take2
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - nency-dotnet-core-application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Measure artifact size before compression
        run: |
          du -sh ${{env.DOTNET_ROOT}}/myapp
        shell: bash

      - name: Compress artifact
        run: |
          cd ${{env.DOTNET_ROOT}}
          zip -r myapp.zip myapp
        working-directory: ${{env.DOTNET_ROOT}}

      - name: Measure artifact size after compression
        run: |
          du -sh ${{env.DOTNET_ROOT}}/myapp.zip
        shell: bash

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nency-dotnet-core-application'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7DA76E03FA3D4A729711506FA98F7219 }}
          package: .
